// Shared request gate for dk's bundled local servers (pivot CSS + CORS proxy).
// Plain Node — no electron imports — the spawned server processes require it.
//
// The servers are no-auth and loopback-bound, so the remaining attacker is a
// web page in some browser on this machine. The gate shuts that out with a
// per-install secret (DK_GATE_TOKEN, generated by servers.cjs). A request is
// authorized when it carries the secret:
//   1. header `x-dk-token` — the Electron shell injects this on app traffic, or
//   2. cookie `dk-token` — a browser "blessed" via the token URL, or
//   3. query `?dk-token=<secret>` — answered with a SameSite=Strict cookie and
//      a redirect to the same URL minus the param (the blessing flow), or
//   4. (opt-in, proxy only) an Origin/Referer on the allowOrigins list — app
//      pages in a blessed browser call the proxy with plain fetch(), which
//      doesn't attach cookies cross-port; a hostile page can't forge Origin.
// Anything else gets a bare 401 with no CORS headers. No token → gate off
// (standalone dev runs of the servers stay open, as before the gate existed).

'use strict';

const HEADER = 'x-dk-token';
const COOKIE = 'dk-token';

// Endpoints that are PUBLIC by Solid/OIDC design and must pass the gate
// un-authenticated, otherwise third-party login is impossible:
//   - a WebID profile document is publicly dereferenceable (it's the user's
//     public identity; CSS's own server-side ownership check fetches it too),
//   - the OIDC discovery + provider endpoints are how any external Solid app
//     authenticates against this server.
// Everything else (the rest of the pod) stays gated.
function isPublicEndpoint(req) {
  let p;
  try { p = new URL(req.url, 'http://localhost').pathname; } catch { return false; }
  if (p === '/.well-known/openid-configuration') return true;
  if (p.startsWith('/.oidc/')) return true;
  if (req.method === 'GET' && /\/profile\/card$/.test(p)) return true;   // any pod's public WebID doc
  return false;
}

function cookieValue(header, name) {
  for (const part of String(header || '').split(';')) {
    const i = part.indexOf('=');
    if (i > 0 && part.slice(0, i).trim() === name) return part.slice(i + 1).trim();
  }
  return undefined;
}

function makeGate(token, { allowOrigins = [] } = {}) {
  // gate(req, res) → true when the gate handled the response (caller stops).
  function gate(req, res) {
    if (!token) return false;
    if (req.headers[HEADER] === token) return false;
    if (cookieValue(req.headers.cookie, COOKIE) === token) return false;

    const url = new URL(req.url, 'http://localhost');
    if (url.searchParams.get(COOKIE) === token) {
      url.searchParams.delete(COOKIE);
      res.writeHead(302, {
        'set-cookie': `${COOKIE}=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=31536000`,
        'location': url.pathname + url.search,
      });
      res.end();
      return true;
    }

    const from = req.headers.origin || req.headers.referer || '';
    if (allowOrigins.some((o) => from === o || from.startsWith(o + '/'))) return false;

    if (isPublicEndpoint(req)) return false;   // public WebID / OIDC endpoints

    res.writeHead(401, { 'content-type': 'text/plain' });
    res.end('data-kitchen: missing or bad token\n');
    return true;
  }

  // Websocket upgrades have no res to answer with — just allowed or not.
  gate.upgradeOk = (req) => !token
    || req.headers[HEADER] === token
    || cookieValue(req.headers.cookie, COOKIE) === token;

  return gate;
}

module.exports = { makeGate };
